GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6192b4f783636f0795215b03


###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Kyle",
    "subscribedToChannel": "Web Dev Simplified"
}
